info <- read.table("info.tsv", header=TRUE)
hla <- read.table("hla.tsv", header=TRUE)
et_split_ST <- split(info, info$ethnicity)
et_split <- split(info, info$ethnicity)
write.table(hla[et_split$asian$sample,], "hla_asian.tsv", quote=FALSE, sep='\t')
write.table(hla[et_split$arab$sample,], "hla_arab.tsv", quote=FALSE, sep='\t')
write.table(hla[et_split$austronasian$sample,], "hla_austronasian.tsv", quote=FALSE, sep='\t')
write.table(hla[et_split$black$sample,], "hla_black.tsv", quote=FALSE, sep='\t')
write.table(hla[et_split$caucasian$sample,], "hla_caucasian.tsv", quote=FALSE, sep='\t')
quit()
